# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c4ec2922f5e20435c51c429a50d0f4b305f8dff7724fdc230873634f6b1d10616eef4b479110b5c5204aa82739aff150289c91ff759b632839c1cab6eb93abd

test:
  secret_key_base: e33cfdcf777041a9163738eb71f1f5d7d8c80c955219f3c414ac7e596c03c5c69851523d5e9deb02d0900b5a9347452408c87d4cf6cec07e72f99a213ddfe1ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
